---
title: "ggjebb"
subtitle: "kind plotting"
author: "ggplot functions helpful labeling and easy comparisons"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include = F}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
```


## Calc count and percent

```{r}
calc_count_and_percent <- function(data, group_var, facet_group_var){

group_var <- enquo(group_var)
facet_group_var <- enquo(facet_group_var)

  data %>%
  count(!!group_var, !!facet_group_var) %>%
  group_by(!!facet_group_var) %>%
  mutate(percent = (100*n/sum(n)) %>% round(1))

}
```



---

`r chunk_reveal("prep")`

```{r prep, include = FALSE}
Titanic %>% 
  data.frame() %>% 
  uncount(Freq) %>% 
  sample_frac(1, replace = F) %>% 
  janitor::clean_names() -> 
tidy_titanic  
```


---

`r chunk_reveal("countpercent")`

```{r countpercent, include = F}  
tidy_titanic %>% 
  calc_count_and_percent(group_var = survived, 
                         facet_group_var = sex) 
```

---


```{r}
geom_text_count <- function(nudge_y = 0, position = 
               position_dodge2(width = .9,
                               preserve = "single"), ...){
  
  stat_count(geom = "text",
             aes(label = after_stat(count),
                 y = after_stat(count) + nudge_y),
             vjust = 0,
             position = position,...
             ) 
  
}

geom_text_count_percent <- function(nudge_y = 0, 
                                    lineheight = .85, 
                                    position = position_dodge2(width = .9,
                               preserve = "single"), ...){
  
  stat_count(geom = "text",
             aes(label = paste0(after_stat(count), "\n(",
                                
                                round(
                                  100*(..count..)/
                                    tapply(..count..,..PANEL..,sum)[..PANEL..], 
                                      1), "%)" ),
                 y = after_stat(count) + nudge_y),
             vjust = 0,
             lineheight = lineheight,
             position = position, ...
             ) 
}

# https://stackoverflow.com/questions/4725339/percentage-on-y-lab-in-a-faceted-ggplot-barchart
geom_bar(aes(y = (..count..)/tapply(..count..,..PANEL..,sum)[..PANEL..]))

```

```{r textcount, include = F}
tidy_titanic %>% 
  ggplot() +
  aes( x = 1) + 
  geom_bar(position = "dodge") + 
  # geom_text_count(nudge_y = 100) + 
  aes(x = survived) + 
  aes(color = sex) + 
  geom_text_count_percent(nudge_y = 10)
```

---

# Old school alternative

`r chunk_reveal("old_school")`

```{r old_school, include = F}
tidy_titanic %>% 
  ggplot() +
  aes( x = 1) + 
  geom_bar(position = "dodge") + 
  stat_count(geom = "text",
             aes(label = after_stat(count),
                 y = after_stat(count) + 65),
             vjust = 0,
             position =
               position_dodge2(width = .9,
                               preserve = "single"),
             ) + 
  aes(x = survived) + 
  aes(fill = sex) + 
  facet_grid(rows = vars(class)) + 
  facet_grid(rows = vars(class),
             cols = vars(age))
```


---

# geom_bar_waldo

`r chunk_reveal("waldo_manual")`

```{r waldo_manual, include = F}
set.seed(1243)
tidy_titanic %>% 
  sample_n(50) %>% 
  count(class, age, sex, survived, 
        .drop = FALSE) %>% 
  ggplot() +
  aes(x = survived) + 
  aes(y = n) +
  geom_col(position = "dodge") + 
  aes(fill = sex) + 
  facet_grid(rows = vars(class)) + 
  facet_grid(rows = vars(class),
             cols = vars(age))
```



---

# geom_coltrace manual

`r chunk_reveal("geom_coltrace_manual")`

```{r geom_coltrace_manual, include = F}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  count(continent) %>% 
  ggplot() +
  aes(x = continent) + 
  aes(y = n) +
  geom_col(position = "dodge") +
  geom_line() + 
  geom_line(aes(group = -1L), color = "red")
```

---

```{r}
ggplot(data = cars) + 
  aes(x = dist) + 
  geom_histogram() + 
  stat_bin(geom = "line", line_type = "dotted") + 
  stat_bin(geom = "text", aes(label = ..count.., y = ..count.. + 1))

#percentage
faithful %>% 
  bind_rows(faithful, faithful, faithful) %>% 
  mutate(grp = sample(0:1, replace  = T, size = 272*4)) ->
big_faithful

ggplot(data = big_faithful) +
  aes(x = eruptions) +
  facet_wrap(~grp) +
  stat_bin(aes(y = 100*(..count..)/
                        tapply(..count..,..PANEL..,sum)[..PANEL..]
             )) +
  stat_bin(geom = "line", aes(y = 100*(..count..)/
                        tapply(..count..,..PANEL..,sum)[..PANEL..]
             ))

# group
ggplot(data = big_faithful) +
  aes(x = eruptions) +
  aes(group = grp) +
  aes(linetype = factor(grp)) +
  stat_bin(data = . %>% filter(grp ==1), aes(y = 100*(..count..)/
                        tapply(X = ..count..,INDEX = ..PANEL..,FUN = sum)[..PANEL..]
             )) +
  facet_wrap(~grp) +
  stat_bin(geom = "line", 
           position = "identity",
           aes(y = 100*(..count..)/
                        tapply(..count..,..group..,sum)[..group..]))

```


---

# geom_coltrace new geom



```{r}
Statcoltrace <-
  ggplot2::ggproto("Statcoltrace",
                   ggplot2::Stat,
                   compute_group = function(data, scales) {

                                    data.frame(x = as.numeric(as.factor(data$x)),
                                               y = data$y)
                                  },

                                  required_aes = c("x", "y")
)

geom_coltrace <- function(mapping = NULL, data = NULL,
                                   position = "identity", na.rm = FALSE, show.legend = NA,
                                   inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = Statcoltrace, geom = ggplot2::GeomLine, data = data, mapping = mapping,
    position = position, show.legend = show.legend, inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}
```


---

`r chunk_reveal("geom_coltrace")`

```{r geom_coltrace, include = F}
gapminder::gapminder %>% 
  filter(year == 2002) %>% 
  count(continent) %>% 
  ggplot() +
  aes(x = continent) + 
  aes(y = n) +
  geom_col() +
  geom_coltrace(linetype = "dashed")

gapminder::gapminder %>% 
  group_by(year, continent) %>% 
  summarise(median_pop = median(pop)) %>% 
  ggplot() +
  aes(x = continent) + 
  aes(y = median_pop) +
  geom_col() +
  geom_coltrace(aes(group = year))


```


